spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - path=/**
        
        - id: product-service
          uri: lb://product-service
          predicates:
            - path=/**

        - id: cart-service
          uri: lb://cart-service
          predicates:
            - path=/**

server:
  port: 8080